// <auto-generated />
using HomePage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomePage.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20241003033541_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomePage.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tommy",
                            Grade = "A",
                            LastName = "Wells"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Eli",
                            Grade = "B",
                            LastName = "Ashby"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Emily",
                            Grade = "C",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Michael",
                            Grade = "B+",
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Amanda",
                            Grade = "A-",
                            LastName = "Christie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
